add zellij rename tab

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -81,3 +81,37 @@ export EDITOR=nvim
 
 source ~/.local/bin/tools.sh
 
+# -------------------- hook for zellij tab name ---------------------
+function change_tab_title() {
+    local title=$1
+    command nohup zellij action rename-tab $title >/dev/null 2>&1
+}
+
+function set_tab_to_working_dir() {
+
+    local title=$PWD
+    if [[ $title == $HOME ]]; then
+        title="~"
+    else
+        title=${title##*/}
+    fi
+
+    local result=$?
+    # uncomment the following to show the exit code after a failed command
+    if [[ $result -gt 0 ]]; then
+        title="$title [$result]" 
+    fi
+
+    change_tab_title $title
+}
+
+function set_tab_to_command_line() {
+    local cmdline=$1
+    change_tab_title $cmdline
+}
+
+if [[ -n $ZELLIJ ]]; then
+    add-zsh-hook precmd set_tab_to_working_dir
+    add-zsh-hook preexec set_tab_to_command_line
+fi
+# -------------------- hook for zellij tab name end ---------------------
